name: sismoney
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.0+1
  smooth_page_indicator: ^1.2.1
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.8
  cloud_firestore_odm: ^1.0.0-dev.88
  json_annotation: ^4.9.0
  skeletonizer: ^2.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  cloud_firestore_odm_generator: ^1.0.0-dev.90
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/img/robot.png
    - lib/assets/img/google-icon.png
    - lib/assets/img/circle-avatar.png
    - lib/assets/img/empty-box.png

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: lib/assets/fonts/JetBrainsMono-Regular.ttf